# Generated by Django 3.0.6 on 2020-05-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Входное изображение')),
                ('name', models.CharField(max_length=200, verbose_name='Название картинки')),
            ],
        ),
    ]
