# Generated by Django 3.0.6 on 2020-05-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Выходное изображение')),
                ('name', models.CharField(max_length=200, verbose_name='Название картинки')),
                ('sigma_color', models.IntegerField(verbose_name='SigmaColor')),
                ('sigma_space', models.IntegerField(verbose_name='SigmaSpace')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
            ],
        ),
    ]
